### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by Lumiga** [perfectwebteam/bytevarnish#10]
Beste Sander,
Ik hoorde van Byte dat er een nieuwe versie beschikbaar was. 
Weet jij toevallig waar kan ik de release notes kan terugvinden?
Alvast bedankt.

**Comment by sanderpotjer** [comment]
Op dit moment zijn die er nog niet, zullen we met de volgende release wel gaan toevoegen. 

In de afgelopen release zijn in ieder geval #3 en #9 opgelost.

**Comment by Lumiga** [comment]
Oké bedankt!
