### ISSUE TITLE
Device detection

### ISSUE THREAD

**Issue by hans2103** [perfectwebteam/bytevarnish#6]
René Kreijveld (@renekreijveld) wrote a UserAgentDetection plugin for Joomla.
https://github.com/renekreijveld/UserAgentDetector
It uses the Mobile Detect script from https://github.com/serbanghita/Mobile-Detect

The general idea is that you can serve different kind of content to different kind of devices. 
Would be cool if this option can be implemented in the plugin too.

background information: 
http://spin.atomicobject.com/2013/02/11/varnish-cache-mobile-devices/

**Comment by sanderpotjer** [comment]
Dat zou kunnen, maar dan moet de Byte VCL dat ook ondersteunen. Leuk idee voor een latere versie!
