### ISSUE TITLE
Door ingelogde gebruikers bezochte pagina's worden niet uitgesloten door Varnish

### ISSUE THREAD

**Issue by geertvansoest** [perfectwebteam/bytevarnish#8]
Hoi,

Wij maken nu voor de tweede keer met veel plezier gebruik van de Varnish Cache plugin van Byte. Echter zijn we daarbij tegen een bug aangelopen. 

De door ons geconstateerde bug is dat de door ingelogde gebruikers bezochte pagina’s ook door Varnish gecached worden (als die pagina nog niet eerder in de Varnish Cache is opgenomen). Waardoor het dus kan voorkomen dat niet-ingelogde gebruikers de pagina’s zien voor wel-ingelogde gebruikers, met bijvoorbeeld bovenaan een gebruikersnaam en een knop ‘Uitloggen’.

Wij hebben dit probleem opgelost door het toevoegen van onderstaande code onderaan in de functie _onBeforeRender()_ in het bestand _/plugins/system/bytevarnish/bytevarnish.php_: 
![varnish](https://cloud.githubusercontent.com/assets/6870951/11423831/31ede758-9448-11e5-82ad-47adc26b3f41.png)

We hebben deze bug ook gemeld bij Byte Support, die ons erop wezen dat dit ook mogelijk is door het toesturen van een "'Vary: Cookie'" header in plaats van een "Cache-Control" header, maar daarmee hebben wij nog niet geëxperimenteerd.

We zien jullie reactie graag tegemoet.

**Comment by sanderpotjer** [comment]
@geertvansoest dank voor het doorgeven van de bug! Dit is inderdaad het geval als ingelogde en niet-ingelogde gebruikers via dezelfde url verschillende content te zien krijgen. We gaan je suggestie verwerken en een update uitbrengen, dank!

**Comment by geertvansoest** [comment]
@sanderpotjer Geen probleem. :-) Heb je enig idee wanneer we de nieuwe versie kunnen downloaden?

**Comment by sanderpotjer** [comment]
@geertvansoest begin volgende week!

**Comment by sanderpotjer** [comment]
@geertvansoest ik heb dit even nader bekeken en het is toch niet helemaal juist. Als een pagina eenmaal in de varnish cache zit heb je aan de voorgestelde code verder niets, want die wordt dan namelijk niet aangeroepen (pagina komt direct uit varnish). Als een pagina nog niet in de cache zit voorkom je inderdaad wel dat deze gecached wordt als een ingelogde gebruiker de pagina bezoekt, doet een gast dat echter zit de pagina weer in de cache. 

Om die reden is er een `onUserLogin` en `onUserLogout` dat een `NO_CACHE` cookie plaatst. https://github.com/perfectwebteam/bytevarnish/blob/master/packages/plg_system_bytevarnish/bytevarnish.php#L95

Je zou kunnen nagaan of die cookies niet of onjuist geplaatst werden bij het inloggen op de site.

**Comment by geertvansoest** [comment]
@sanderpotjer 
Dat klopt inderdaad. Met de cookie NO_CACHE wordt correct afgevangen dat ingelogde gebruikers NIET de door Varnish gecachete code krijgen uitgeserveerd. 

Het probleem is echter dat pagina's wél gecached WORDEN als de bezoeker is ingelogd (en de pagina nog niet voorkomt in de Varnish cache). Hierdoor kan het voorkomen dat de 'ingelogde variant' van een pagina gecached wordt en dat deze vervolgens ook uitgeserveerd wordt voor niet-ingelogde gebruikers (met bijvoorbeeld de gebruikersnaam van de ingelogde gebruiker en een knop om 'uit te loggen').

"Als een pagina nog niet in de cache zit voorkom je inderdaad wel dat deze gecached wordt als een ingelogde gebruiker de pagina bezoekt, doet een gast dat echter zit de pagina weer in de cache." Dit is dus eigenlijk precies wat we met deze code willen bereiken.
